# Generated by Django 5.0.6 on 2024-07-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
